# Generated by Django 5.2.7 on 2025-11-21 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('category', models.CharField(choices=[('ШАУРМА', 'Шаурма'), ('НА МАНГАЛЕ', 'На мангале'), ('ЛАХМАДЖО', 'Лахмаджо'), ('ФАЛАФЕЛ', 'Фалафел'), ('СУПЫ', 'Супы'), ('НАПИТКИ', 'Напитки')], max_length=20, verbose_name='Категория')),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu_images/', verbose_name='Изображение')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступно')),
            ],
            options={
                'verbose_name': 'Пункт меню',
                'verbose_name_plural': 'Пункты меню',
                'ordering': ['category', 'name'],
            },
        ),
    ]
