# Generated by Django 5.2.7 on 2025-11-21 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voske_dzerq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('ШАУРМА', 'Շաուրմա'), ('НА МАНГАЛЕ', 'Մանգալի վրա'), ('ЛАХМАДЖО', 'Լահմաջո'), ('ФАЛАФЕЛ', 'Ֆալաֆել'), ('СУПЫ', 'Ապուրներ'), ('НАПИТКИ', 'Խմիչքներ'), ('ЗАКУСКИ', 'Խորտիկներ')], max_length=20, verbose_name='Категория'),
        ),
    ]
