# Generated by Django 5.2.7 on 2025-12-08 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voske_dzerq', '0003_alter_menuitem_category_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['category', 'name'], 'verbose_name': 'Menu Item', 'verbose_name_plural': 'Menu Items'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AddField(
            model_name='menuitem',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Description (English)'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='description_hy',
            field=models.TextField(blank=True, verbose_name='Description (Armenian)'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='description_ru',
            field=models.TextField(blank=True, verbose_name='Description (Russian)'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='name_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Name (English)'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='name_hy',
            field=models.CharField(blank=True, max_length=200, verbose_name='Name (Armenian)'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='name_ru',
            field=models.CharField(blank=True, max_length=200, verbose_name='Name (Russian)'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('ШАУРМА', 'Shawarma'), ('НА МАНГАЛЕ', 'Grilled'), ('ЛАХМАДЖО', 'Lahmajo'), ('ФАЛАФЕЛ', 'Falafel'), ('СУПЫ', 'Soups'), ('НАПИТКИ', 'Drinks'), ('ЗАКУСКИ', 'Snacks')], max_length=20, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu_images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Available'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(max_length=200, verbose_name='Customer Name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_processed',
            field=models.BooleanField(default=False, verbose_name='Processed'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_details',
            field=models.TextField(verbose_name='Order Details'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total Price'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
